const { EmbedBuilder } = require("discord.js");
const db = require("./database");
const joins = new Map(), messageWindows = new Map();
function bucket(map,key,windowMs){const now=Date.now(),arr=map.get(key)||[];while(arr.length&&now-arr[0]>windowMs)arr.shift();arr.push(now);map.set(key,arr);return arr;}
async function alert(guild,type,severity,details,sendLog){db.createProactiveAlert(guild.id,type,severity,details);db.log(guild.id,null,null,"PROACTIVE_ALERT",type+": "+details);if(sendLog){const e=new EmbedBuilder().setTitle("🚨 Overseer Proactive Alert").setDescription(details).addFields({name:"Type",value:type,inline:true},{name:"Severity",value:severity+"/5",inline:true}).setTimestamp();await sendLog(guild,e);}}
async function onMemberJoin(member,sendLog){const s=db.settings(member.guild.id),a=bucket(joins,member.guild.id,60000),t=Number(s.join_flood_threshold||5);if(s.proactive_enabled&&a.length===t)await alert(member.guild,"JOIN_FLOOD",4,`${a.length} members joined within approximately one minute. Review for a possible raid or invite spike.`,sendLog);}
async function onMessage(message,sendLog){if(!message.guild||message.author.bot)return;db.recordMemberMessage(message.guild.id,message.author.id);const s=db.settings(message.guild.id),a=bucket(messageWindows,message.guild.id,60000),t=Number(s.activity_spike_threshold||80);if(s.proactive_enabled&&a.length===t)await alert(message.guild,"ACTIVITY_SPIKE",2,`Approximately ${a.length} messages were observed in one minute. Staff may want to check activity.`,sendLog);}
function buildReport(guild,days=1){const since=new Date(Date.now()-days*86400000).toISOString(),cut=Date.now()-days*86400000;const events=db.eventCounts(guild.id,since),warnings=db.recentWarnings(guild.id,100).filter(x=>new Date(x.created_at+"Z").getTime()>=cut).length,incidents=db.automodIncidents(guild.id,200).filter(x=>new Date(x.created_at+"Z").getTime()>=cut).length,alerts=db.proactiveAlertCount(guild.id,since),active=db.topActiveMembers(guild.id,5);return{warnings,incidents,alerts,eventText:events.length?events.map(x=>`${x.event_type}: ${x.n}`).join(" • "):"No recorded events",activeText:active.length?active.map((x,n)=>`${n+1}. <@${x.user_id}> — ${x.message_count} messages`).join("\n"):"No message activity recorded yet."};}
async function runScheduledReports(client){const now=new Date(),hour=now.getUTCHours(),date=now.toISOString().slice(0,10);for(const guild of client.guilds.cache.values()){const s=db.reportSettings(guild.id);if(!s.enabled||!s.channel_id||Number(s.hour_utc)!==hour||s.last_sent_date===date)continue;if(s.frequency==="weekly"&&now.getUTCDay()!==1)continue;const ch=guild.channels.cache.get(s.channel_id)||await guild.channels.fetch(s.channel_id).catch(()=>null);if(!ch?.isTextBased())continue;const days=s.frequency==="weekly"?7:1,r=buildReport(guild,days);const e=new EmbedBuilder().setTitle(`📊 Overseer ${s.frequency==="weekly"?"Weekly":"Daily"} Intelligence Report`).setDescription(`Server: **${guild.name}**\nMembers now: **${guild.memberCount}**`).addFields({name:"Warnings",value:String(r.warnings),inline:true},{name:"AutoMod incidents",value:String(r.incidents),inline:true},{name:"Proactive alerts",value:String(r.alerts),inline:true},{name:"Event activity",value:r.eventText.slice(0,1000)},{name:"Most active members",value:r.activeText.slice(0,1000)}).setTimestamp();await ch.send({embeds:[e]}).catch(()=>{});db.updateReportSettings(guild.id,{last_sent_date:date});}}
module.exports={onMemberJoin,onMessage,buildReport,runScheduledReports};
